sudo: required
services:
  - docker

before_install:
  - docker build -t andrzejburzynski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t andrzejburzynski/multi-client ./client
  - docker build -t andrzejburzynski/multi-nginx ./nginx
  - docker build -t andrzejburzynski/multi-server ./server
  - docker build -t andrzejburzynski/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push andrzejburzynski/multi-client
  - docker push andrzejburzynski/multi-nginx
  - docker push andrzejburzynski/multi-server
  - docker push andrzejburzynski/multi-worker
